name = "Polynomial"
uuid = "6f680cd8-de0f-4705-b77b-527ca4408bd0"
version = "0.1.0"
authors = ["tangxiangong <tangxiangong@gmail.com>"]

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[compat]
FFTW = "1.10.0"
